// Code generated by goyacc -o ql.go -v ql.output -p ql ql.y. DO NOT EDIT.

//line ql.y:2
package parser

import __yyfmt__ "fmt"

//line ql.y:2

//line ql.y:5
type qlSymType struct {
	yys int
	*Token

	// scoped control flow expressions
	*ScopeDef
	*ExprBlock
	*ConditionalExpr
	*ForExpr

	ControlFlowExpr
	Expr

	Declaration
	Declarations []Declaration

	Statements []ControlFlowExpr
	Arguments  []*Argument

	TypeSpec
}

const LEX_ERROR = 57346
const BLOCK_COMMENT_END = 57347
const COMMENT = 57348
const L_BRACE = 57349
const R_BRACE = 57350
const L_PAREN = 57351
const R_PAREN = 57352
const L_BRACKET = 57353
const R_BRACKET = 57354
const ASSIGN = 57355
const COLON = 57356
const COMMA = 57357
const DOT = 57358
const STAR_STAR = 57359
const AT = 57360
const SEMICOLON = 57361
const NEWLINE = 57362
const LET = 57363
const IF = 57364
const ELSE = 57365
const FOR = 57366
const RETURN = 57367
const TYPE = 57368
const OR = 57369
const AND = 57370
const NOT = 57371
const LT = 57372
const GT = 57373
const EQ = 57374
const NE = 57375
const LE = 57376
const GE = 57377
const BITWISE_OR = 57378
const BITWISE_AND = 57379
const XOR = 57380
const L_SHIFT = 57381
const R_SHIFT = 57382
const ADD = 57383
const SUB = 57384
const MUL = 57385
const DIV = 57386
const MOD = 57387
const UNARY = 57388
const IDENT = 57389
const BYTE_LITERAL = 57390
const STRING_LITERAL = 57391
const INT_LITERAL = 57392
const FLOAT_LITERAL = 57393
const BOOL_LITERAL = 57394
const BOOL_TYPE = 57395
const INT_TYPE = 57396
const UINT_TYPE = 57397
const FLOAT_TYPE = 57398
const BYTE_TYPE = 57399
const STRING_TYPE = 57400
const NOOP = 57401

var qlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"BLOCK_COMMENT_END",
	"COMMENT",
	"L_BRACE",
	"R_BRACE",
	"L_PAREN",
	"R_PAREN",
	"L_BRACKET",
	"R_BRACKET",
	"ASSIGN",
	"COLON",
	"COMMA",
	"DOT",
	"STAR_STAR",
	"AT",
	"SEMICOLON",
	"NEWLINE",
	"LET",
	"IF",
	"ELSE",
	"FOR",
	"RETURN",
	"TYPE",
	"OR",
	"AND",
	"NOT",
	"LT",
	"GT",
	"EQ",
	"NE",
	"LE",
	"GE",
	"BITWISE_OR",
	"BITWISE_AND",
	"XOR",
	"L_SHIFT",
	"R_SHIFT",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"UNARY",
	"IDENT",
	"BYTE_LITERAL",
	"STRING_LITERAL",
	"INT_LITERAL",
	"FLOAT_LITERAL",
	"BOOL_LITERAL",
	"BOOL_TYPE",
	"INT_TYPE",
	"UINT_TYPE",
	"FLOAT_TYPE",
	"BYTE_TYPE",
	"STRING_TYPE",
	"NOOP",
}
var qlStatenames = [...]string{}

const qlEofCode = 1
const qlErrCode = 2
const qlInitialStackSize = 16

//line ql.y:739

//line yacctab:1
var qlExca = [...]int{
	-1, 0,
	1, 2,
	-2, 22,
	-1, 1,
	1, -1,
	-2, 0,
	-1, 3,
	1, 3,
	-2, 22,
	-1, 64,
	10, 68,
	-2, 22,
	-1, 71,
	8, 10,
	-2, 22,
	-1, 113,
	8, 11,
	-2, 22,
}

const qlPrivate = 57344

const qlLast = 379

var qlAct = [...]int{

	12, 68, 69, 21, 33, 74, 9, 115, 18, 135,
	107, 7, 106, 114, 57, 36, 35, 71, 65, 66,
	145, 17, 60, 54, 55, 56, 62, 24, 25, 26,
	27, 28, 72, 30, 31, 32, 29, 139, 37, 38,
	84, 85, 86, 87, 88, 89, 90, 91, 92, 93,
	94, 95, 96, 97, 98, 99, 100, 101, 61, 58,
	125, 137, 59, 103, 64, 110, 105, 58, 111, 18,
	121, 63, 124, 117, 118, 52, 53, 54, 55, 56,
	67, 119, 17, 116, 127, 71, 1, 62, 24, 25,
	26, 27, 28, 77, 30, 31, 32, 29, 3, 78,
	79, 80, 81, 82, 83, 2, 11, 4, 10, 120,
	122, 34, 70, 123, 23, 22, 109, 108, 113, 130,
	112, 16, 132, 134, 129, 116, 138, 128, 136, 37,
	38, 13, 76, 140, 71, 15, 20, 141, 134, 18,
	19, 144, 143, 102, 142, 0, 0, 147, 146, 72,
	104, 73, 17, 0, 0, 0, 0, 14, 24, 25,
	26, 27, 28, 0, 30, 31, 32, 29, 0, 8,
	5, 13, 0, 0, 0, 15, 6, 77, 0, 18,
	0, 0, 0, 78, 79, 80, 81, 82, 83, 0,
	0, 0, 17, 0, 0, 0, 0, 14, 24, 25,
	26, 27, 28, 133, 30, 31, 32, 29, 75, 8,
	39, 40, 0, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 0,
	135, 0, 0, 0, 71, 77, 0, 0, 0, 0,
	0, 78, 79, 80, 81, 82, 83, 131, 0, 0,
	0, 0, 0, 0, 39, 40, 126, 41, 42, 43,
	44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
	54, 55, 56, 39, 40, 0, 41, 42, 43, 44,
	45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
	55, 56, 39, 40, 0, 41, 42, 43, 44, 45,
	46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
	56, 40, 0, 41, 42, 43, 44, 45, 46, 47,
	48, 49, 50, 51, 52, 53, 54, 55, 56, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 48, 49, 50, 51, 52,
	53, 54, 55, 56, 49, 50, 51, 52, 53, 54,
	55, 56, 50, 51, 52, 53, 54, 55, 56,
}
var qlPact = [...]int{

	150, -1000, -1000, 150, -1000, -1000, -31, 19, -1000, -1000,
	-1000, -1000, 265, -33, 49, 40, 55, -21, -21, -1000,
	71, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, 127, -1000, 188, -1000, -1000, -1000, -21,
	-21, -21, -21, -21, -21, -21, -21, -21, -21, -21,
	-21, -21, -21, -21, -21, -21, -21, 130, -1000, -21,
	-1000, -35, 41, -37, -21, -1000, 299, -21, -1000, -1000,
	-1000, 110, -21, -21, -1000, 46, -1000, -1000, -1000, -1000,
	-1000, -1000, -1000, -1000, 283, 299, 309, 309, 309, 309,
	309, 309, 318, 326, 333, 34, 34, -20, -20, -1000,
	-1000, -1000, -21, 57, 46, -1000, -21, -1000, 62, 45,
	265, 246, 76, 110, -1000, -1000, 19, 227, 183, -1000,
	-1000, -21, 48, -1000, -1000, -21, -1000, -1000, -1000, -1000,
	14, 78, -1000, -38, 78, 41, -1000, -21, 265, 10,
	-3, -1000, -1000, -1000, -1000, 10, -1000, -1000,
}
var qlPgo = [...]int{

	0, 140, 136, 132, 6, 121, 0, 120, 118, 117,
	116, 4, 3, 1, 115, 2, 114, 112, 13, 11,
	108, 106, 5, 107, 105, 98, 86, 7,
}
var qlR1 = [...]int{

	0, 26, 24, 24, 25, 25, 23, 23, 23, 23,
	7, 7, 8, 8, 27, 27, 18, 18, 19, 19,
	19, 19, 11, 11, 3, 3, 3, 3, 3, 3,
	22, 22, 12, 13, 14, 15, 15, 15, 15, 15,
	15, 16, 17, 17, 20, 20, 20, 20, 21, 21,
	4, 1, 1, 1, 1, 1, 2, 2, 2, 2,
	5, 5, 5, 5, 5, 5, 5, 5, 9, 9,
	10, 10, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
	6, 6, 6,
}
var qlR2 = [...]int{

	0, 1, 0, 1, 1, 2, 1, 3, 4, 2,
	0, 1, 1, 2, 1, 1, 1, 2, 1, 1,
	1, 1, 0, 2, 1, 1, 1, 1, 1, 1,
	1, 1, 2, 3, 2, 3, 4, 5, 6, 5,
	6, 2, 3, 4, 4, 5, 6, 3, 2, 4,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 4, 1, 1, 1, 3, 4, 0, 1,
	1, 3, 1, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 2,
}
var qlChk = [...]int{

	-1000, -26, -24, -25, -23, 20, 26, -19, 59, -4,
	-20, -21, -6, 21, 47, 25, -5, 42, 29, -1,
	-2, -12, -14, -16, 48, 49, 50, 51, 52, 57,
	54, 55, 56, -11, -23, 47, -27, 19, 20, 27,
	28, 30, 31, 32, 33, 34, 35, 36, 37, 38,
	39, 40, 41, 42, 43, 44, 45, 47, 18, 13,
	-4, 18, 47, 16, 9, -6, -6, 9, -13, -15,
	-17, 7, 22, 24, -22, 20, -3, 47, 53, 54,
	55, 56, 57, 58, -6, -6, -6, -6, -6, -6,
	-6, -6, -6, -6, -6, -6, -6, -6, -6, -6,
	-6, -6, 13, -22, 20, -4, 47, 47, -9, -10,
	-6, -6, -7, -8, -18, -27, -19, -6, -6, -22,
	-4, 13, -22, -4, 10, 15, 10, 8, -18, -27,
	-13, 20, -12, 20, -11, 47, -4, 13, -6, 23,
	-13, -12, -4, -15, -13, 23, -15, -13,
}
var qlDef = [...]int{

	-2, -2, 1, -2, 4, 6, 0, 0, 18, 19,
	20, 21, 50, 0, 60, 22, 72, 22, 22, 61,
	0, 63, 64, 65, 51, 52, 53, 54, 55, 56,
	57, 58, 59, 0, 5, 0, 9, 14, 15, 22,
	22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
	22, 22, 22, 22, 22, 22, 22, 0, 23, 22,
	48, 0, 60, 0, -2, 91, 92, 22, 32, 34,
	41, -2, 22, 22, 7, 0, 30, 31, 24, 25,
	26, 27, 28, 29, 73, 74, 75, 76, 77, 78,
	79, 80, 81, 82, 83, 84, 85, 86, 87, 88,
	89, 90, 22, 0, 0, 47, 22, 66, 0, 69,
	70, 0, 0, -2, 12, 16, 0, 0, 22, 8,
	44, 22, 0, 49, 67, 22, 62, 33, 13, 17,
	35, 0, 42, 22, 0, 0, 45, 22, 71, 0,
	36, 43, 46, 37, 39, 0, 38, 40,
}
var qlTok1 = [...]int{

	1,
}
var qlTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
	52, 53, 54, 55, 56, 57, 58, 59,
}
var qlTok3 = [...]int{
	0,
}

var qlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	qlDebug        = 0
	qlErrorVerbose = false
)

type qlLexer interface {
	Lex(lval *qlSymType) int
	Error(s string)
}

type qlParser interface {
	Parse(qlLexer) int
	Lookahead() int
}

type qlParserImpl struct {
	lval  qlSymType
	stack [qlInitialStackSize]qlSymType
	char  int
}

func (p *qlParserImpl) Lookahead() int {
	return p.char
}

func qlNewParser() qlParser {
	return &qlParserImpl{}
}

const qlFlag = -1000

func qlTokname(c int) string {
	if c >= 1 && c-1 < len(qlToknames) {
		if qlToknames[c-1] != "" {
			return qlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func qlStatname(s int) string {
	if s >= 0 && s < len(qlStatenames) {
		if qlStatenames[s] != "" {
			return qlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func qlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !qlErrorVerbose {
		return "syntax error"
	}

	for _, e := range qlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + qlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := qlPact[state]
	for tok := TOKSTART; tok-1 < len(qlToknames); tok++ {
		if n := base + tok; n >= 0 && n < qlLast && qlChk[qlAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if qlDef[state] == -2 {
		i := 0
		for qlExca[i] != -1 || qlExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; qlExca[i] >= 0; i += 2 {
			tok := qlExca[i]
			if tok < TOKSTART || qlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if qlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += qlTokname(tok)
	}
	return res
}

func qllex1(lex qlLexer, lval *qlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = qlTok1[0]
		goto out
	}
	if char < len(qlTok1) {
		token = qlTok1[char]
		goto out
	}
	if char >= qlPrivate {
		if char < qlPrivate+len(qlTok2) {
			token = qlTok2[char-qlPrivate]
			goto out
		}
	}
	for i := 0; i < len(qlTok3); i += 2 {
		token = qlTok3[i+0]
		if token == char {
			token = qlTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = qlTok2[1] /* unknown char */
	}
	if qlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", qlTokname(token), uint(char))
	}
	return char, token
}

func qlParse(qllex qlLexer) int {
	return qlNewParser().Parse(qllex)
}

func (qlrcvr *qlParserImpl) Parse(qllex qlLexer) int {
	var qln int
	var qlVAL qlSymType
	var qlDollar []qlSymType
	_ = qlDollar // silence set and not used
	qlS := qlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	qlstate := 0
	qlrcvr.char = -1
	qltoken := -1 // qlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		qlstate = -1
		qlrcvr.char = -1
		qltoken = -1
	}()
	qlp := -1
	goto qlstack

ret0:
	return 0

ret1:
	return 1

qlstack:
	/* put a state and value onto the stack */
	if qlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", qlTokname(qltoken), qlStatname(qlstate))
	}

	qlp++
	if qlp >= len(qlS) {
		nyys := make([]qlSymType, len(qlS)*2)
		copy(nyys, qlS)
		qlS = nyys
	}
	qlS[qlp] = qlVAL
	qlS[qlp].yys = qlstate

qlnewstate:
	qln = qlPact[qlstate]
	if qln <= qlFlag {
		goto qldefault /* simple state */
	}
	if qlrcvr.char < 0 {
		qlrcvr.char, qltoken = qllex1(qllex, &qlrcvr.lval)
	}
	qln += qltoken
	if qln < 0 || qln >= qlLast {
		goto qldefault
	}
	qln = qlAct[qln]
	if qlChk[qln] == qltoken { /* valid shift */
		qlrcvr.char = -1
		qltoken = -1
		qlVAL = qlrcvr.lval
		qlstate = qln
		if Errflag > 0 {
			Errflag--
		}
		goto qlstack
	}

qldefault:
	/* default state action */
	qln = qlDef[qlstate]
	if qln == -2 {
		if qlrcvr.char < 0 {
			qlrcvr.char, qltoken = qllex1(qllex, &qlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if qlExca[xi+0] == -1 && qlExca[xi+1] == qlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			qln = qlExca[xi+0]
			if qln < 0 || qln == qltoken {
				break
			}
		}
		qln = qlExca[xi+1]
		if qln < 0 {
			goto ret0
		}
	}
	if qln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			qllex.Error(qlErrorMessage(qlstate, qltoken))
			Nerrs++
			if qlDebug >= 1 {
				__yyfmt__.Printf("%s", qlStatname(qlstate))
				__yyfmt__.Printf(" saw %s\n", qlTokname(qltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for qlp >= 0 {
				qln = qlPact[qlS[qlp].yys] + qlErrCode
				if qln >= 0 && qln < qlLast {
					qlstate = qlAct[qln] /* simulate a shift of "error" */
					if qlChk[qlstate] == qlErrCode {
						goto qlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if qlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", qlS[qlp].yys)
				}
				qlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if qlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", qlTokname(qltoken))
			}
			if qltoken == qlEofCode {
				goto ret1
			}
			qlrcvr.char = -1
			qltoken = -1
			goto qlnewstate /* try again in the same state */
		}
	}

	/* reduction by production qln */
	if qlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", qln, qlStatname(qlstate))
	}

	qlnt := qln
	qlpt := qlp
	_ = qlpt // guard against "declared and not used"

	qlp -= qlR2[qln]
	// qlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if qlp+1 >= len(qlS) {
		nyys := make([]qlSymType, len(qlS)*2)
		copy(nyys, qlS)
		qlS = nyys
	}
	qlVAL = qlS[qlp+1]

	/* consult goto table to find next state */
	qln = qlR1[qln]
	qlg := qlPgo[qln]
	qlj := qlg + qlS[qlp].yys + 1

	if qlj >= qlLast {
		qlstate = qlAct[qlg]
	} else {
		qlstate = qlAct[qlj]
		if qlChk[qlstate] != -qln {
			qlstate = qlAct[qlg]
		}
	}
	// dummy call; replaced with literal code
	switch qlnt {

	case 1:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:104
		{
			nodes := make([]Node, 0, len(qlDollar[1].Declarations))
			for _, node := range qlDollar[1].Declarations {
				nodes = append(nodes, node)
			}
			qllex.(*parseContext).setParsed(nodes)
		}
	case 2:
		qlDollar = qlS[qlpt-0 : qlpt+1]
//line ql.y:114
		{
			qlVAL.Declarations = nil
		}
	case 3:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:117
		{
			qlVAL.Declarations = qlDollar[1].Declarations
		}
	case 4:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:122
		{
			if qlDollar[1].Declaration != nil {
				qlVAL.Declarations = append(qlVAL.Declarations, qlDollar[1].Declaration)
			}
		}
	case 5:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:127
		{
			if qlDollar[2].Declaration != nil {
				qlVAL.Declarations = append(qlDollar[1].Declarations, qlDollar[2].Declaration)
			}
		}
	case 6:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:135
		{
			// do nothing
			qlVAL.Declaration = nil
		}
	case 7:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:139
		{
			qlVAL.Declaration = &TypeDef{
				Location: qlDollar[1].Token.Loc().Merge(qlDollar[3].TypeSpec.Loc()),
				Type:     qlDollar[1].Token,
				Name:     qlDollar[2].Token,
				TypeSpec: qlDollar[3].TypeSpec,
			}
		}
	case 8:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:147
		{
			qlVAL.Declaration = &TypeDef{
				Location: qlDollar[1].Token.Loc().Merge(qlDollar[4].TypeSpec.Loc()),
				Type:     qlDollar[1].Token,
				Name:     qlDollar[2].Token,
				TypeSpec: qlDollar[4].TypeSpec,
			}
		}
	case 9:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:155
		{
			// TODO(patrick): remove this
			qlVAL.Declaration = &FakeDeclaration{
				Location:   qlDollar[1].ControlFlowExpr.Loc(),
				Expression: qlDollar[1].ControlFlowExpr,
			}
		}
	case 10:
		qlDollar = qlS[qlpt-0 : qlpt+1]
//line ql.y:165
		{ // NOTE: empty expr block evals to unit
			qlVAL.Statements = nil
		}
	case 11:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:168
		{
			qlVAL.Statements = qlDollar[1].Statements
		}
	case 12:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:174
		{
			if qlDollar[1].ControlFlowExpr != nil {
				qlVAL.Statements = append(qlVAL.Statements, qlDollar[1].ControlFlowExpr)
			}
		}
	case 13:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:179
		{
			if qlDollar[2].ControlFlowExpr != nil {
				qlVAL.Statements = append(qlDollar[1].Statements, qlDollar[2].ControlFlowExpr)
			}
		}
	case 14:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:187
		{
			// do nothing
		}
	case 15:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:190
		{
			// do nothing
		}
	case 16:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:196
		{
			qlVAL.ControlFlowExpr = nil
		}
	case 17:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:199
		{
			qlVAL.ControlFlowExpr = qlDollar[1].ControlFlowExpr
		}
	case 18:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:205
		{
			qlVAL.ControlFlowExpr = &Noop{
				Location: qlDollar[1].Token.Location,
				Value:    qlDollar[1].Token,
			}
		}
	case 19:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:211
		{
			qlVAL.ControlFlowExpr = &EvalExpr{
				Location:   qlDollar[1].Expr.Loc(),
				Expression: qlDollar[1].Expr,
			}
		}
	case 20:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:217
		{
			qlVAL.ControlFlowExpr = qlDollar[1].ControlFlowExpr
		}
	case 21:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:220
		{
			qlVAL.ControlFlowExpr = qlDollar[1].ControlFlowExpr
		}
	case 22:
		qlDollar = qlS[qlpt-0 : qlpt+1]
//line ql.y:226
		{
			qlVAL.ScopeDef = nil
		}
	case 23:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:229
		{
			qlVAL.ScopeDef = &ScopeDef{
				Location: qlDollar[1].Token.Location.Merge(qlDollar[2].Token.Location),
				Name:     qlDollar[1].Token,
				At:       qlDollar[2].Token,
			}
		}
	case 24:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:239
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 25:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:242
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 26:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:245
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 27:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:248
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 28:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:251
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 29:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:254
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 30:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:260
		{
			qlVAL.TypeSpec = &ScalarType{
				Location: qlDollar[1].Token.Loc(),
				Type:     qlDollar[1].Token,
			}
		}
	case 31:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:266
		{
			qlVAL.TypeSpec = &NamedType{
				Location: qlDollar[1].Token.Loc(),
				Type:     qlDollar[1].Token,
			}
		}
	case 32:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:275
		{
			qlVAL.ExprBlock = qlDollar[2].ExprBlock
			if qlDollar[1].ScopeDef != nil {
				qlVAL.ExprBlock.Location = qlDollar[1].ScopeDef.Location.Merge(qlDollar[2].ExprBlock.Location)
				qlVAL.ExprBlock.ScopeDef = qlDollar[1].ScopeDef
			}
		}
	case 33:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:285
		{
			qlVAL.ExprBlock = &ExprBlock{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[3].Token.Loc()),
				LBrace:     qlDollar[1].Token,
				Statements: qlDollar[2].Statements,
				RBrace:     qlDollar[3].Token,
			}
		}
	case 34:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:296
		{
			qlVAL.ConditionalExpr = qlDollar[2].ConditionalExpr
			if qlDollar[1].ScopeDef != nil {
				qlVAL.ConditionalExpr.Location = qlDollar[1].ScopeDef.Location.Merge(qlDollar[2].ConditionalExpr.Location)
				qlVAL.ConditionalExpr.ScopeDef = qlDollar[1].ScopeDef
			}
		}
	case 35:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:306
		{
			qlVAL.ConditionalExpr = &ConditionalExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[3].ExprBlock.Loc()),
				If:         qlDollar[1].Token,
				Predicate:  qlDollar[2].Expr,
				TrueClause: qlDollar[3].ExprBlock,
			}
		}
	case 36:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:314
		{
			qlVAL.ConditionalExpr = &ConditionalExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[4].ExprBlock.Loc()),
				If:         qlDollar[1].Token,
				Predicate:  qlDollar[2].Expr,
				TrueClause: qlDollar[4].ExprBlock,
			}
		}
	case 37:
		qlDollar = qlS[qlpt-5 : qlpt+1]
//line ql.y:322
		{
			qlVAL.ConditionalExpr = &ConditionalExpr{
				Location:    qlDollar[1].Token.Loc().Merge(qlDollar[5].ConditionalExpr.Loc()),
				If:          qlDollar[1].Token,
				Predicate:   qlDollar[2].Expr,
				TrueClause:  qlDollar[3].ExprBlock,
				Else:        qlDollar[4].Token,
				FalseClause: qlDollar[5].ConditionalExpr,
			}
		}
	case 38:
		qlDollar = qlS[qlpt-6 : qlpt+1]
//line ql.y:332
		{
			qlVAL.ConditionalExpr = &ConditionalExpr{
				Location:    qlDollar[1].Token.Loc().Merge(qlDollar[6].ConditionalExpr.Loc()),
				If:          qlDollar[1].Token,
				Predicate:   qlDollar[2].Expr,
				TrueClause:  qlDollar[4].ExprBlock,
				Else:        qlDollar[5].Token,
				FalseClause: qlDollar[6].ConditionalExpr,
			}
		}
	case 39:
		qlDollar = qlS[qlpt-5 : qlpt+1]
//line ql.y:342
		{
			qlVAL.ConditionalExpr = &ConditionalExpr{
				Location:    qlDollar[1].Token.Loc().Merge(qlDollar[5].ExprBlock.Loc()),
				If:          qlDollar[1].Token,
				Predicate:   qlDollar[2].Expr,
				TrueClause:  qlDollar[3].ExprBlock,
				Else:        qlDollar[4].Token,
				FalseClause: qlDollar[5].ExprBlock,
			}
		}
	case 40:
		qlDollar = qlS[qlpt-6 : qlpt+1]
//line ql.y:352
		{
			qlVAL.ConditionalExpr = &ConditionalExpr{
				Location:    qlDollar[1].Token.Loc().Merge(qlDollar[6].ExprBlock.Loc()),
				If:          qlDollar[1].Token,
				Predicate:   qlDollar[2].Expr,
				TrueClause:  qlDollar[4].ExprBlock,
				Else:        qlDollar[5].Token,
				FalseClause: qlDollar[6].ExprBlock,
			}
		}
	case 41:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:365
		{
			qlVAL.ForExpr = qlDollar[2].ForExpr
			if qlDollar[1].ScopeDef != nil {
				qlVAL.ForExpr.Location = qlDollar[1].ScopeDef.Location.Merge(qlDollar[2].ForExpr.Location)
				qlVAL.ForExpr.ScopeDef = qlDollar[1].ScopeDef
			}
		}
	case 42:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:375
		{
			qlVAL.ForExpr = &ForExpr{
				Location:  qlDollar[1].Token.Location.Merge(qlDollar[3].ExprBlock.Location),
				For:       qlDollar[1].Token,
				Predicate: qlDollar[2].Expr,
				Body:      qlDollar[3].ExprBlock,
			}
		}
	case 43:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:383
		{
			qlVAL.ForExpr = &ForExpr{
				Location:  qlDollar[1].Token.Location.Merge(qlDollar[4].ExprBlock.Location),
				For:       qlDollar[1].Token,
				Predicate: qlDollar[2].Expr,
				Body:      qlDollar[4].ExprBlock,
			}
		}
	case 44:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:394
		{
			qlVAL.ControlFlowExpr = &AssignExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[4].Expr.Loc()),
				Let:        qlDollar[1].Token,
				Name:       qlDollar[2].Token,
				Assign:     qlDollar[3].Token,
				Expression: qlDollar[4].Expr,
			}
		}
	case 45:
		qlDollar = qlS[qlpt-5 : qlpt+1]
//line ql.y:404
		{
			qlVAL.ControlFlowExpr = &AssignExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[5].Expr.Loc()),
				Let:        qlDollar[1].Token,
				Name:       qlDollar[2].Token,
				TypeSpec:   qlDollar[3].TypeSpec,
				Assign:     qlDollar[4].Token,
				Expression: qlDollar[5].Expr,
			}
		}
	case 46:
		qlDollar = qlS[qlpt-6 : qlpt+1]
//line ql.y:415
		{
			qlVAL.ControlFlowExpr = &AssignExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[6].Expr.Loc()),
				Let:        qlDollar[1].Token,
				Name:       qlDollar[2].Token,
				TypeSpec:   qlDollar[4].TypeSpec,
				Assign:     qlDollar[5].Token,
				Expression: qlDollar[6].Expr,
			}
		}
	case 47:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:426
		{
			qlVAL.ControlFlowExpr = &AssignExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[3].Expr.Loc()),
				Name:       qlDollar[1].Token,
				Assign:     qlDollar[2].Token,
				Expression: qlDollar[3].Expr,
			}
		}
	case 48:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:437
		{
			qlVAL.ControlFlowExpr = &ReturnExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[2].Expr.Loc()),
				Return:     qlDollar[1].Token,
				Expression: qlDollar[2].Expr,
			}
		}
	case 49:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:444
		{
			qlVAL.ControlFlowExpr = &ReturnExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[4].Expr.Loc()),
				Return:     qlDollar[1].Token,
				At:         qlDollar[2].Token,
				Label:      qlDollar[3].Token,
				Expression: qlDollar[4].Expr,
			}
		}
	case 50:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:456
		{
			qlVAL.Expr = qlDollar[1].Expr
		}
	case 51:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:462
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 52:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:465
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 53:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:468
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 54:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:471
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 55:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:474
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 56:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:480
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 57:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:483
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 58:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:486
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 59:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:489
		{
			qlVAL.Token = qlDollar[1].Token
		}
	case 60:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:496
		{
			qlVAL.Expr = &Identifier{
				Location: qlDollar[1].Token.Location,
				Value:    qlDollar[1].Token,
			}
		}
	case 61:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:502
		{
			qlVAL.Expr = &Literal{
				Location: qlDollar[1].Token.Location,
				Value:    qlDollar[1].Token,
			}
		}
	case 62:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:508
		{
			qlVAL.Expr = &TypeConversion{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[4].Token.Loc()),
				Type:       qlDollar[1].Token,
				LParen:     qlDollar[2].Token,
				Expression: qlDollar[3].Expr,
				RParen:     qlDollar[4].Token,
			}
		}
	case 63:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:517
		{
			qlVAL.Expr = qlDollar[1].ExprBlock
		}
	case 64:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:520
		{
			qlVAL.Expr = qlDollar[1].ConditionalExpr
		}
	case 65:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:523
		{
			qlVAL.Expr = qlDollar[1].ForExpr
		}
	case 66:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:526
		{
			qlVAL.Expr = &Accessor{
				Location:    qlDollar[1].Expr.Loc().Merge(qlDollar[3].Token.Loc()),
				PrimaryExpr: qlDollar[1].Expr,
				Dot:         qlDollar[2].Token,
				Name:        qlDollar[3].Token,
			}
		}
	case 67:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:534
		{
			qlVAL.Expr = &Invocation{
				Location:   qlDollar[1].Expr.Loc().Merge(qlDollar[4].Token.Loc()),
				Expression: qlDollar[1].Expr,
				LParen:     qlDollar[2].Token,
				Arguments:  qlDollar[3].Arguments,
				RParen:     qlDollar[4].Token,
			}
		}
	case 68:
		qlDollar = qlS[qlpt-0 : qlpt+1]
//line ql.y:546
		{ // empty
			qlVAL.Arguments = nil
		}
	case 69:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:549
		{
			qlVAL.Arguments = qlDollar[1].Arguments
		}
	case 70:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:555
		{
			qlVAL.Arguments = []*Argument{
				&Argument{
					Location:   qlDollar[1].Expr.Loc(),
					Expression: qlDollar[1].Expr,
				},
			}
		}
	case 71:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:563
		{
			qlDollar[1].Arguments[len(qlDollar[1].Arguments)-1].Location = qlDollar[1].Arguments[len(qlDollar[1].Arguments)-1].Location.Merge(qlDollar[2].Token.Loc())
			qlDollar[1].Arguments[len(qlDollar[1].Arguments)-1].Comma = qlDollar[2].Token
			qlVAL.Arguments = append(qlDollar[1].Arguments,
				&Argument{
					Location:   qlDollar[3].Expr.Loc(),
					Expression: qlDollar[3].Expr,
				})
		}
	case 72:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:576
		{
			qlVAL.Expr = qlDollar[1].Expr
		}
	case 73:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:579
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 74:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:587
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 75:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:595
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 76:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:603
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 77:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:611
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 78:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:619
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 79:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:627
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 80:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:635
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 81:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:643
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 82:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:651
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 83:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:659
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 84:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:667
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 85:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:675
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 86:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:683
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 87:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:691
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 88:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:699
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 89:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:707
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 90:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:715
		{
			qlVAL.Expr = &BinaryExpr{
				Location: qlDollar[1].Expr.Loc().Merge(qlDollar[3].Expr.Loc()),
				Left:     qlDollar[1].Expr,
				Op:       qlDollar[2].Token,
				Right:    qlDollar[3].Expr,
			}
		}
	case 91:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:723
		{
			qlVAL.Expr = &UnaryExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[2].Expr.Loc()),
				Op:         qlDollar[1].Token,
				Expression: qlDollar[2].Expr,
			}
		}
	case 92:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:730
		{
			qlVAL.Expr = &UnaryExpr{
				Location:   qlDollar[1].Token.Loc().Merge(qlDollar[2].Expr.Loc()),
				Op:         qlDollar[1].Token,
				Expression: qlDollar[2].Expr,
			}
		}
	}
	goto qlstack /* stack new state and value */
}
