// Code generated by goyacc -o ql.go -v ql.output -p ql ql.y. DO NOT EDIT.

//line ql.y:2
package parser

import __yyfmt__ "fmt"

//line ql.y:2

type strLoc struct {
	str string
	loc Location
}

//line ql.y:11
type qlSymType struct {
	yys int
	Location

	strLoc

	*AssignExpr
	Expr

	Nodes []Node
}

const LEX_ERROR = 57346
const ASSIGN = 57347
const L_BRACE = 57348
const R_BRACE = 57349
const L_PAREN = 57350
const R_PAREN = 57351
const SEMICOLON = 57352
const NEWLINE = 57353
const COMMA = 57354
const DOT = 57355
const OR = 57356
const AND = 57357
const NOT = 57358
const LT = 57359
const GT = 57360
const EQ = 57361
const NE = 57362
const LE = 57363
const GE = 57364
const BITWISE_OR = 57365
const BITWISE_AND = 57366
const SHIFT_LEFT = 57367
const SHIFT_RIGHT = 57368
const ADD = 57369
const SUB = 57370
const MUL = 57371
const DIV = 57372
const MOD = 57373
const UNARY = 57374
const IDENTIFIER = 57375
const COMMENT_GROUP = 57376
const LET = 57377

var qlToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"LEX_ERROR",
	"ASSIGN",
	"L_BRACE",
	"R_BRACE",
	"L_PAREN",
	"R_PAREN",
	"SEMICOLON",
	"NEWLINE",
	"COMMA",
	"DOT",
	"OR",
	"AND",
	"NOT",
	"LT",
	"GT",
	"EQ",
	"NE",
	"LE",
	"GE",
	"BITWISE_OR",
	"BITWISE_AND",
	"SHIFT_LEFT",
	"SHIFT_RIGHT",
	"ADD",
	"SUB",
	"MUL",
	"DIV",
	"MOD",
	"UNARY",
	"IDENTIFIER",
	"COMMENT_GROUP",
	"LET",
}
var qlStatenames = [...]string{}

const qlEofCode = 1
const qlErrCode = 2
const qlInitialStackSize = 16

//line ql.y:196

//line yacctab:1
var qlExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const qlPrivate = 57344

const qlLast = 163

var qlAct = [...]int{

	14, 45, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 39, 42, 43, 75,
	5, 6, 44, 69, 49, 50, 51, 52, 53, 54,
	55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
	65, 68, 70, 37, 38, 39, 9, 23, 24, 74,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 31, 32, 33, 34, 35,
	36, 37, 38, 39, 76, 77, 78, 23, 24, 71,
	25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
	35, 36, 37, 38, 39, 24, 12, 25, 26, 27,
	28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
	38, 39, 22, 67, 21, 33, 34, 35, 36, 37,
	38, 39, 17, 32, 33, 34, 35, 36, 37, 38,
	39, 22, 40, 21, 16, 47, 46, 41, 66, 18,
	48, 17, 35, 36, 37, 38, 39, 3, 13, 72,
	73, 7, 8, 16, 20, 10, 11, 19, 18, 1,
	2, 15, 4,
}
var qlPact = [...]int{

	-14, -1000, 141, -1000, -1000, -1000, 13, -14, -14, 91,
	-1000, -1000, 125, -1000, 63, 124, 125, 125, -1000, -1000,
	-1000, 125, 106, 125, 125, 125, 125, 125, 125, 125,
	125, 125, 125, 125, 125, 125, 125, 125, 125, 125,
	125, -10, -1000, -15, 33, 72, 139, -1000, -1000, 80,
	-15, 42, 42, 42, 42, 42, 42, 99, 90, 115,
	115, 14, 14, -1000, -1000, -1000, 40, 7, 63, -1000,
	-1000, -1000, 106, 106, -1000, 125, -1000, -1000, 63,
}
var qlPgo = [...]int{

	0, 162, 135, 161, 147, 160, 159, 0, 157, 154,
	138, 1, 136, 113,
}
var qlR1 = [...]int{

	0, 6, 5, 5, 5, 4, 4, 2, 3, 3,
	3, 3, 3, 9, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, 7, 8, 11, 11, 11, 12, 12,
	10, 10, 13, 13, 1,
}
var qlR2 = [...]int{

	0, 1, 1, 3, 3, 1, 1, 1, 1, 1,
	1, 4, 3, 3, 1, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 2, 2, 3, 1, 3, 3, 1, 1,
	0, 1, 1, 3, 4,
}
var qlChk = [...]int{

	-1000, -6, -5, -4, -1, 34, 35, 10, 11, 33,
	-4, -4, 5, -2, -7, -3, 28, 16, 33, -8,
	-9, 8, 6, 14, 15, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	8, 13, -7, -7, -7, -11, -12, -2, 34, -7,
	-7, -7, -7, -7, -7, -7, -7, -7, -7, -7,
	-7, -7, -7, -7, -7, -7, -10, -13, -7, 33,
	9, 7, 10, 11, 9, 12, -11, -11, -7,
}
var qlDef = [...]int{

	0, -2, 1, 2, 5, 6, 0, 0, 0, 0,
	3, 4, 0, 44, 7, 14, 0, 0, 8, 9,
	10, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
	40, 0, 32, 33, 0, 0, 35, 38, 39, 15,
	16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
	26, 27, 28, 29, 30, 31, 0, 41, 42, 13,
	12, 34, 0, 0, 11, 0, 36, 37, 43,
}
var qlTok1 = [...]int{

	1,
}
var qlTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
	22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
	32, 33, 34, 35,
}
var qlTok3 = [...]int{
	0,
}

var qlErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	qlDebug        = 0
	qlErrorVerbose = false
)

type qlLexer interface {
	Lex(lval *qlSymType) int
	Error(s string)
}

type qlParser interface {
	Parse(qlLexer) int
	Lookahead() int
}

type qlParserImpl struct {
	lval  qlSymType
	stack [qlInitialStackSize]qlSymType
	char  int
}

func (p *qlParserImpl) Lookahead() int {
	return p.char
}

func qlNewParser() qlParser {
	return &qlParserImpl{}
}

const qlFlag = -1000

func qlTokname(c int) string {
	if c >= 1 && c-1 < len(qlToknames) {
		if qlToknames[c-1] != "" {
			return qlToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func qlStatname(s int) string {
	if s >= 0 && s < len(qlStatenames) {
		if qlStatenames[s] != "" {
			return qlStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func qlErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !qlErrorVerbose {
		return "syntax error"
	}

	for _, e := range qlErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + qlTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := qlPact[state]
	for tok := TOKSTART; tok-1 < len(qlToknames); tok++ {
		if n := base + tok; n >= 0 && n < qlLast && qlChk[qlAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if qlDef[state] == -2 {
		i := 0
		for qlExca[i] != -1 || qlExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; qlExca[i] >= 0; i += 2 {
			tok := qlExca[i]
			if tok < TOKSTART || qlExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if qlExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += qlTokname(tok)
	}
	return res
}

func qllex1(lex qlLexer, lval *qlSymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = qlTok1[0]
		goto out
	}
	if char < len(qlTok1) {
		token = qlTok1[char]
		goto out
	}
	if char >= qlPrivate {
		if char < qlPrivate+len(qlTok2) {
			token = qlTok2[char-qlPrivate]
			goto out
		}
	}
	for i := 0; i < len(qlTok3); i += 2 {
		token = qlTok3[i+0]
		if token == char {
			token = qlTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = qlTok2[1] /* unknown char */
	}
	if qlDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", qlTokname(token), uint(char))
	}
	return char, token
}

func qlParse(qllex qlLexer) int {
	return qlNewParser().Parse(qllex)
}

func (qlrcvr *qlParserImpl) Parse(qllex qlLexer) int {
	var qln int
	var qlVAL qlSymType
	var qlDollar []qlSymType
	_ = qlDollar // silence set and not used
	qlS := qlrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	qlstate := 0
	qlrcvr.char = -1
	qltoken := -1 // qlrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		qlstate = -1
		qlrcvr.char = -1
		qltoken = -1
	}()
	qlp := -1
	goto qlstack

ret0:
	return 0

ret1:
	return 1

qlstack:
	/* put a state and value onto the stack */
	if qlDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", qlTokname(qltoken), qlStatname(qlstate))
	}

	qlp++
	if qlp >= len(qlS) {
		nyys := make([]qlSymType, len(qlS)*2)
		copy(nyys, qlS)
		qlS = nyys
	}
	qlS[qlp] = qlVAL
	qlS[qlp].yys = qlstate

qlnewstate:
	qln = qlPact[qlstate]
	if qln <= qlFlag {
		goto qldefault /* simple state */
	}
	if qlrcvr.char < 0 {
		qlrcvr.char, qltoken = qllex1(qllex, &qlrcvr.lval)
	}
	qln += qltoken
	if qln < 0 || qln >= qlLast {
		goto qldefault
	}
	qln = qlAct[qln]
	if qlChk[qln] == qltoken { /* valid shift */
		qlrcvr.char = -1
		qltoken = -1
		qlVAL = qlrcvr.lval
		qlstate = qln
		if Errflag > 0 {
			Errflag--
		}
		goto qlstack
	}

qldefault:
	/* default state action */
	qln = qlDef[qlstate]
	if qln == -2 {
		if qlrcvr.char < 0 {
			qlrcvr.char, qltoken = qllex1(qllex, &qlrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if qlExca[xi+0] == -1 && qlExca[xi+1] == qlstate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			qln = qlExca[xi+0]
			if qln < 0 || qln == qltoken {
				break
			}
		}
		qln = qlExca[xi+1]
		if qln < 0 {
			goto ret0
		}
	}
	if qln == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			qllex.Error(qlErrorMessage(qlstate, qltoken))
			Nerrs++
			if qlDebug >= 1 {
				__yyfmt__.Printf("%s", qlStatname(qlstate))
				__yyfmt__.Printf(" saw %s\n", qlTokname(qltoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for qlp >= 0 {
				qln = qlPact[qlS[qlp].yys] + qlErrCode
				if qln >= 0 && qln < qlLast {
					qlstate = qlAct[qln] /* simulate a shift of "error" */
					if qlChk[qlstate] == qlErrCode {
						goto qlstack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if qlDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", qlS[qlp].yys)
				}
				qlp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if qlDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", qlTokname(qltoken))
			}
			if qltoken == qlEofCode {
				goto ret1
			}
			qlrcvr.char = -1
			qltoken = -1
			goto qlnewstate /* try again in the same state */
		}
	}

	/* reduction by production qln */
	if qlDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", qln, qlStatname(qlstate))
	}

	qlnt := qln
	qlpt := qlp
	_ = qlpt // guard against "declared and not used"

	qlp -= qlR2[qln]
	// qlp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if qlp+1 >= len(qlS) {
		nyys := make([]qlSymType, len(qlS)*2)
		copy(nyys, qlS)
		qlS = nyys
	}
	qlVAL = qlS[qlp+1]

	/* consult goto table to find next state */
	qln = qlR1[qln]
	qlg := qlPgo[qln]
	qlj := qlg + qlS[qlp].yys + 1

	if qlj >= qlLast {
		qlstate = qlAct[qlg]
	} else {
		qlstate = qlAct[qlj]
		if qlChk[qlstate] != -qln {
			qlstate = qlAct[qlg]
		}
	}
	// dummy call; replaced with literal code
	switch qlnt {

	case 1:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:53
		{
			qllex.(*parseContext).setParsed(qlDollar[1].Nodes)
		}
	case 2:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:60
		{
			qlVAL.Nodes = []Node{qlDollar[1].Expr}
		}
	case 3:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:63
		{
			qlVAL.Nodes = append(qlDollar[1].Nodes, qlDollar[3].Expr)
		}
	case 4:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:66
		{
			qlVAL.Nodes = append(qlDollar[1].Nodes, qlDollar[3].Expr)
		}
	case 5:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:73
		{
			qlVAL.Expr = qlDollar[1].AssignExpr
		}
	case 6:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:76
		{
		}
	case 7:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:81
		{
		}
	case 8:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:87
		{
			qlVAL.Expr = &Identifier{
				Value: qlDollar[1].strLoc.str,
			}
		}
	case 9:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:92
		{
		}
	case 10:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:94
		{
		}
	case 11:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:96
		{
		}
	case 12:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:98
		{
		}
	case 13:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:103
		{
		}
	case 14:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:109
		{
		}
	case 15:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:111
		{
		}
	case 16:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:113
		{
		}
	case 17:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:115
		{
		}
	case 18:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:117
		{
		}
	case 19:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:119
		{
		}
	case 20:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:121
		{
		}
	case 21:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:123
		{
		}
	case 22:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:125
		{
		}
	case 23:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:127
		{
		}
	case 24:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:129
		{
		}
	case 25:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:131
		{
		}
	case 26:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:133
		{
		}
	case 27:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:135
		{
		}
	case 28:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:137
		{
		}
	case 29:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:139
		{
		}
	case 30:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:141
		{
		}
	case 31:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:143
		{
		}
	case 32:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:145
		{
		}
	case 33:
		qlDollar = qlS[qlpt-2 : qlpt+1]
//line ql.y:147
		{
		}
	case 34:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:152
		{
		}
	case 35:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:158
		{
		}
	case 36:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:160
		{
		}
	case 37:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:162
		{
		}
	case 38:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:167
		{
		}
	case 39:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:169
		{
		}
	case 40:
		qlDollar = qlS[qlpt-0 : qlpt+1]
//line ql.y:174
		{ // empty
		}
	case 41:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:176
		{
		}
	case 42:
		qlDollar = qlS[qlpt-1 : qlpt+1]
//line ql.y:181
		{
		}
	case 43:
		qlDollar = qlS[qlpt-3 : qlpt+1]
//line ql.y:183
		{
		}
	case 44:
		qlDollar = qlS[qlpt-4 : qlpt+1]
//line ql.y:188
		{
			qlVAL.AssignExpr = &AssignExpr{
				Name:       qlDollar[2].strLoc.str,
				Expression: qlDollar[4].Expr,
			}
		}
	}
	goto qlstack /* stack new state and value */
}
